In [9]:
from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_ROOT = Path.cwd().parent

RAW_DATA = PROJECT_ROOT / "data" / "raw"
CLEAN_DATA = PROJECT_ROOT / "data" / "clean"
FIGURES = PROJECT_ROOT / "figures"

In [10]:
print("Project root:", PROJECT_ROOT)
print("Raw data:", RAW_DATA)

Project root: /Users/jannoelvero/Documents/spotify_project
Raw data: /Users/jannoelvero/Documents/spotify_project/data/raw

In [12]:
df_track = pd.read_csv(RAW_DATA / "track_data_final.csv")
df_spotify = pd.read_csv(RAW_DATA / "spotify_data_clean.csv")

In [13]:
print("Track dataset:", df_track.shape)
print("Spotify dataset:", df_spotify.shape)

Track dataset: (8778, 15)
Spotify dataset: (8582, 15)

In [14]:
#visually compare the structure and values.
display(df_track.head())
display(df_spotify.head())

,track_id,track_name,track_number,track_popularity,track_duration_ms,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type
0,6pymOcrCnMuCWdgGVTvUgP,3,57,61,213173,False,Britney Spears,80.0,17755451.0,['pop'],325wcm5wMnlfjmKZ8PXIIn,The Singles Collection,2009-11-09,58,compilation
1,2lWc1iJlz2NVcStV5fbtPG,Clouds,1,67,158760,False,BUNT.,69.0,293734.0,['stutter house'],2ArRQNLxf9t0O0gvmG5Vsj,Clouds,2023-01-13,1,single
2,1msEuwSBneBKpVCZQcFTsU,Forever & Always (Taylor’s Version),11,63,225328,False,Taylor Swift,100.0,145396321.0,[],4hDok0OAJd57SGIT8xuWJH,Fearless (Taylor's Version),2021-04-09,26,album
3,7bcy34fBT2ap1L4bfPsl9q,I Didn't Change My Number,2,72,158463,True,Billie Eilish,90.0,118692183.0,[],0JGOiO34nwfUdDrD612dOp,Happier Than Ever,2021-07-30,16,album
4,0GLfodYacy3BJE7AI3A8en,Man Down,7,57,267013,False,Rihanna,90.0,68997177.0,[],5QG3tjE5L9F6O2vCAPph38,Loud,2010-01-01,13,album

,track_id,track_name,track_number,track_popularity,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type,track_duration_min
0,3EJS5LyekDim1Tf5rBFmZl,Trippy Mane (ft. Project Pat),4,0,True,Diplo,77,2812821,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.55
1,1oQW6G2ZiwMuHqlPpP27DB,OMG!,1,0,True,Yelawolf,64,2363438,"country hip hop, southern hip hop",4SUmmwnv0xTjRcLdjczGg2,OMG!,2025-10-31,1,single,3.07
2,7mdkjzoIYlf1rx9EtBpGmU,Hard 2 Find,1,4,True,Riff Raff,48,193302,NaN,3E3zEAL8gUYWaLYB9L7gbp,Hard 2 Find,2025-10-31,1,single,2.55
3,67rW0Zl7oB3qEpD5YWWE5w,Still Get Like That (ft. Project Pat & Starrah),8,30,True,Diplo,77,2813710,moombahton,5QRFnGnBeMGePBKF2xTz5z,"d00mscrvll, Vol. 1",2025-10-31,9,album,1.69
4,15xptTfRBrjsppW0INUZjf,ride me like a harley,2,0,True,Rumelis,48,8682,dark r&b,06FDIpSHYmZAZoyuYtc7kd,come closer / ride me like a harley,2025-10-30,2,single,2.39

In [15]:
print("Track dataset columns:")
print(df_track.columns.tolist())

print("\nSpotify dataset columns:")
print(df_spotify.columns.tolist())

Track dataset columns:
['track_id', 'track_name', 'track_number', 'track_popularity', 'track_duration_ms', 'explicit', 'artist_name', 'artist_popularity', 'artist_followers', 'artist_genres', 'album_id', 'album_name', 'album_release_date', 'album_total_tracks', 'album_type']

Spotify dataset columns:
['track_id', 'track_name', 'track_number', 'track_popularity', 'explicit', 'artist_name', 'artist_popularity', 'artist_followers', 'artist_genres', 'album_id', 'album_name', 'album_release_date', 'album_total_tracks', 'album_type', 'track_duration_min']

In [16]:
print("Track dataset:")
df_track.info()

print("\nSpotify dataset:")
df_spotify.info()

Track dataset:
<class 'pandas.DataFrame'>
RangeIndex: 8778 entries, 0 to 8777
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   track_id            8778 non-null   str
 1   track_name          8776 non-null   str
 2   track_number        8778 non-null   int64
 3   track_popularity    8778 non-null   int64
 4   track_duration_ms   8778 non-null   int64
 5   explicit            8778 non-null   bool
 6   artist_name         8774 non-null   str
 7   artist_popularity   8774 non-null   float64
 8   artist_followers    8774 non-null   float64
 9   artist_genres       8774 non-null   str
 10  album_id            8778 non-null   str
 11  album_name          8776 non-null   str
 12  album_release_date  8778 non-null   str
 13  album_total_tracks  8778 non-null   int64
 14  album_type          8778 non-null   str
dtypes: bool(1), float64(2), int64(4), str(8)
memory usage: 968.8 KB

Spotify dataset:
<class 'pandas.DataFrame'>
RangeIndex: 8582 entries, 0 to 8581
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   track_id            8582 non-null   str
 1   track_name          8582 non-null   str
 2   track_number        8582 non-null   int64
 3   track_popularity    8582 non-null   int64
 4   explicit            8582 non-null   bool
 5   artist_name         8579 non-null   str
 6   artist_popularity   8582 non-null   int64
 7   artist_followers    8582 non-null   int64
 8   artist_genres       5221 non-null   str
 9   album_id            8582 non-null   str
 10  album_name          8582 non-null   str
 11  album_release_date  8582 non-null   str
 12  album_total_tracks  8582 non-null   int64
 13  album_type          8582 non-null   str
 14  track_duration_min  8582 non-null   float64
dtypes: bool(1), float64(1), int64(5), str(8)
memory usage: 947.2 KB

In [17]:
print("Track dataset missing values:")
print(df_track.isnull().sum())

print("\nSpotify dataset missing values:")
print(df_spotify.isnull().sum())

Track dataset missing values:
track_id              0
track_name            2
track_number          0
track_popularity      0
track_duration_ms     0
explicit              0
artist_name           4
artist_popularity     4
artist_followers      4
artist_genres         4
album_id              0
album_name            2
album_release_date    0
album_total_tracks    0
album_type            0
dtype: int64

Spotify dataset missing values:
track_id                 0
track_name               0
track_number             0
track_popularity         0
explicit                 0
artist_name              3
artist_popularity        0
artist_followers         0
artist_genres         3361
album_id                 0
album_name               0
album_release_date       0
album_total_tracks       0
album_type               0
track_duration_min       0
dtype: int64

In [18]:
print("Track dataset duplicates:", df_track.duplicated().sum())
print("Spotify dataset duplicates:", df_spotify.duplicated().sum())

Track dataset duplicates: 0
Spotify dataset duplicates: 0

In [19]:
print("Track dataset unique IDs:", df_track["track_id"].nunique())
print("Spotify dataset unique IDs:", df_spotify["track_id"].nunique())

Track dataset unique IDs: 8778
Spotify dataset unique IDs: 8582

In [20]:
same_columns = df_track.columns.tolist() == df_spotify.columns.tolist()

print("Same columns:", same_columns)

Same columns: False

In [21]:
track_only = df_track[
    ~df_track["track_id"].isin(df_spotify["track_id"])
]

print("Tracks only in track dataset:", len(track_only))

Tracks only in track dataset: 196

In [22]:
track_only.head(10)

,track_id,track_name,track_number,track_popularity,track_duration_ms,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type
19,14iN3o8ptQ8cFVZTEmyQRV,I Kissed A Girl,2,75,179640,False,Katy Perry,83.0,38385499.0,['pop'],3OALgjCs6Lqw41853v4wEQ,One Of The Boys,2008-06-17,13,album
184,47Slg6LuqLaX0VodpSCvPt,Just the Way You Are,2,80,220734,False,Bruno Mars,89.0,75455093.0,[],6J84szYCnMfzEcvIcfWMFL,Doo-Wops & Hooligans,2010-05-11,12,album
200,2ULNeSomDxVNmdDy8VxEBU,22,6,58,230133,False,Taylor Swift,100.0,145396321.0,[],1EoDsNmgTLtmwe1BDAVxV5,Red,2012-10-22,16,album
301,1dEy9Pl81QopSxNsPxXQxv,Stay,9,66,240706,False,Rihanna,90.0,68997177.0,[],4eddbruVtOqw8khwxSH6H2,Unapologetic (Deluxe),2012-12-11,17,album
322,76OGwb5RA9h4FxQPT33ekc,SNAP,1,9,179551,False,Rosa Linn,63.0,467788.0,[],4fb1QzgTJpTk9TBjFzjmlR,SNAP,2022-03-19,1,single
329,15JINEqzVMv3SvJTAXAKED,Love The Way You Lie,15,85,263373,True,Eminem,88.0,104517308.0,"['rap', 'hip hop']",47BiFcV59TQi2s9SkBo2pb,Recovery,2010-06-18,17,album
448,04wODYKrbLNe7LTOaOPX3i,"Sex, Drugs, Etc.",6,0,196784,False,Beach Weather,65.0,1005044.0,[],6ygLpSyAvRSKGZw1LZkxOX,Chit Chat,2016-11-04,6,single
567,6gGBL1uMBcNUOzSYfKreID,Had Some Drinks,1,60,140973,True,Two Feet,67.0,2177177.0,[],5fMrHJYuEt4H17sAV2Mx0N,Had Some Drinks,2017-05-19,1,single
629,5S9Zs5g9lTWnLIboN1pdlU,Fingers Crossed,1,0,175344,False,Lauren Spencer Smith,68.0,1764567.0,[],1UPlwdM0JYNwlDcKbeXrKZ,Fingers Crossed,2022-01-05,1,single
697,2wtHlpYSgC7xEdD3DrSHNL,The Lucky One,13,43,240133,False,Taylor Swift,100.0,145396321.0,[],1KlU96Hw9nlvqpBPlSqcTV,Red (Deluxe Edition),2012-10-22,22,album

In [23]:
#aligning track duration
df_track["track_duration_min"] = df_track["track_duration_ms"] / 60000

df_track = df_track.drop(columns=["track_duration_ms"])

In [24]:
#setting the column order
column_order = [
    "track_id",
    "track_name",
    "track_number",
    "track_popularity",
    "explicit",
    "artist_name",
    "artist_popularity",
    "artist_followers",
    "artist_genres",
    "album_id",
    "album_name",
    "album_release_date",
    "album_total_tracks",
    "album_type",
    "track_duration_min"
]

df_track = df_track[column_order]
df_spotify = df_spotify[column_order]

In [25]:
print("Track dataset:")
print(df_track.columns.tolist())

print("\nSpotify dataset:")
print(df_spotify.columns.tolist())

Track dataset:
['track_id', 'track_name', 'track_number', 'track_popularity', 'explicit', 'artist_name', 'artist_popularity', 'artist_followers', 'artist_genres', 'album_id', 'album_name', 'album_release_date', 'album_total_tracks', 'album_type', 'track_duration_min']

Spotify dataset:
['track_id', 'track_name', 'track_number', 'track_popularity', 'explicit', 'artist_name', 'artist_popularity', 'artist_followers', 'artist_genres', 'album_id', 'album_name', 'album_release_date', 'album_total_tracks', 'album_type', 'track_duration_min']

In [26]:
print("Same columns:", df_track.columns.tolist() == df_spotify.columns.tolist())

Same columns: True

In [27]:
print("Track dataset:", df_track.shape)
print("Spotify dataset:", df_spotify.shape)

Track dataset: (8778, 15)
Spotify dataset: (8582, 15)

In [28]:
#show missing records
df_track[df_track.isnull().any(axis=1)]

,track_id,track_name,track_number,track_popularity,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type,track_duration_min
436,3QhfFRPkhPCR1RMJWV1gde,Radio,8,65,True,NaN,NaN,NaN,NaN,0Dt3FbpMQwjoT5KNAw0IXR,Born To Die – Paradise Edition (Special Version),2012-01-01,24,album,3.576433
1396,2NbsBSshscKIPRG3kwBbfo,Never Felt So Alone,1,68,False,NaN,NaN,NaN,NaN,33JqWTchq6piiQddrRIvJX,Never Felt So Alone,2023-04-07,1,single,2.669433
3618,37ns6v0HK4zMV1PpRLIsbx,NaN,1,0,False,Various Artists,0.0,2777475.0,[],6ZANj7FHgq4Lozaq67DUaW,NaN,0000,1,single,0.000000
3885,5EhZC8GFOVXrpiUW22jncE,Urban Twilight,4,30,False,NaN,NaN,NaN,NaN,1Cog6aZ6NwnJiuINc0LQEU,Darkbloom,2011-04-18,5,single,4.260567
3886,0fM9dEhUFV4MHDuJgrcfOv,How You Get The Girl,10,59,False,NaN,NaN,NaN,NaN,1yGbNOtRIgdIiGHOEBaZWf,1989 (Deluxe),2014-01-01,19,album,4.125550
4170,6N21iOdTYgYjDK1AyS0iUW,NaN,2,0,True,Various Artists,0.0,2777927.0,[],49p6Te0TtN1Ew5qP5GIEQB,NaN,0000,2,single,0.000000

In [29]:
problem_ids = df_track[
    df_track.isnull().any(axis=1)
]["track_id"]

df_spotify[
    df_spotify["track_id"].isin(problem_ids)
]

,track_id,track_name,track_number,track_popularity,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type,track_duration_min
1807,2NbsBSshscKIPRG3kwBbfo,Never Felt So Alone,1,68,False,NaN,0,0,NaN,33JqWTchq6piiQddrRIvJX,Never Felt So Alone,2023-04-07,1,single,2.66
5904,0fM9dEhUFV4MHDuJgrcfOv,How You Get The Girl,10,59,False,Taylor Swift,100,145396321,"country, pop, indie, folk",1yGbNOtRIgdIiGHOEBaZWf,1989 (Deluxe),2014-01-01,19,album,4.12
6517,3QhfFRPkhPCR1RMJWV1gde,Radio,8,65,True,NaN,0,0,NaN,0Dt3FbpMQwjoT5KNAw0IXR,Born To Die – Paradise Edition (Special Version),2012-01-01,24,album,3.57
6679,5EhZC8GFOVXrpiUW22jncE,Urban Twilight,4,30,False,NaN,0,0,NaN,1Cog6aZ6NwnJiuINc0LQEU,Darkbloom,2011-04-18,5,single,4.26

In [30]:
track_only = df_track[
    ~df_track["track_id"].isin(df_spotify["track_id"])
]

print("Tracks only in track dataset:", len(track_only))

Tracks only in track dataset: 196

In [32]:
track_only.isnull().sum()

track_id              0
track_name            2
track_number          0
track_popularity      0
explicit              0
artist_name           0
artist_popularity     0
artist_followers      0
artist_genres         0
album_id              0
album_name            2
album_release_date    0
album_total_tracks    0
album_type            0
track_duration_min    0
dtype: int64

In [33]:
track_only.describe()

,track_number,track_popularity,artist_popularity,artist_followers,album_total_tracks,track_duration_min
count,196.000000,196.000000,196.000000,1.960000e+02,196.000000,196.000000
mean,4.739796,46.831633,78.887755,3.861749e+07,13.357143,3.719879
std,4.103613,33.147181,13.341189,4.077116e+07,6.838428,0.912507
min,1.000000,0.000000,0.000000,5.819000e+04,1.000000,0.000000
25%,2.000000,4.750000,71.000000,4.014090e+06,11.000000,3.277446
50%,3.500000,60.000000,81.000000,2.578887e+07,13.000000,3.657550
75%,6.000000,75.000000,89.000000,6.672064e+07,17.000000,4.055663
max,22.000000,100.000000,100.000000,1.454894e+08,37.000000,7.656433

In [34]:
track_only[
    [
        "track_name",
        "artist_name",
        "track_popularity",
        "artist_popularity",
        "artist_followers",
        "album_release_date",
        "track_duration_min"
    ]
].head(20)

,track_name,artist_name,track_popularity,artist_popularity,artist_followers,album_release_date,track_duration_min
19,I Kissed A Girl,Katy Perry,75,83.0,38385499.0,2008-06-17,2.994000
184,Just the Way You Are,Bruno Mars,80,89.0,75455093.0,2010-05-11,3.678900
200,22,Taylor Swift,58,100.0,145396321.0,2012-10-22,3.835550
301,Stay,Rihanna,66,90.0,68997177.0,2012-12-11,4.011767
322,SNAP,Rosa Linn,9,63.0,467788.0,2022-03-19,2.992517
329,Love The Way You Lie,Eminem,85,88.0,104517308.0,2010-06-18,4.389550
448,"Sex, Drugs, Etc.",Beach Weather,0,65.0,1005044.0,2016-11-04,3.279733
567,Had Some Drinks,Two Feet,60,67.0,2177177.0,2017-05-19,2.349550
629,Fingers Crossed,Lauren Spencer Smith,0,68.0,1764567.0,2022-01-05,2.922400
697,The Lucky One,Taylor Swift,43,100.0,145396321.0,2012-10-22,4.002217
711,D.D.,The Weeknd,50,93.0,112918137.0,2012-11-13,4.573900
713,Chasing Cars,Snow Patrol,3,68.0,3300881.0,2006-01-01,4.465550
778,Don't Wanna Know (feat. Kendrick Lamar),Maroon 5,64,85.0,45764832.0,2018-06-15,3.571083
816,Counting Stars,OneRepublic,1,81.0,18700851.0,2013-01-01,4.287767
835,Romantic Homicide,d4vd,0,79.0,4681304.0,2022-07-20,2.210500
841,Let Me Love You (Until You Learn To Love Yours...,Ne-Yo,43,80.0,10214903.0,2012-01-01,4.193767
885,Space Song,Beach House,75,72.0,2803036.0,2015-08-28,5.341100
914,Let It Go,James Bay,61,67.0,4106573.0,2015-03-23,4.342200
938,Treat You Better,Shawn Mendes,0,81.0,45700057.0,2017-04-20,3.132883
952,State Of Grace - Acoustic,Taylor Swift,40,100.0,145396321.0,2012-10-22,5.384667

In [35]:
print("Zero popularity:", (track_only["track_popularity"] == 0).sum())
print("Zero duration:", (track_only["track_duration_min"] == 0).sum())
print("Zero artist popularity:", (track_only["artist_popularity"] == 0).sum())
print("Zero artist followers:", (track_only["artist_followers"] == 0).sum())

Zero popularity: 18
Zero duration: 2
Zero artist popularity: 2
Zero artist followers: 0

In [36]:
track_only["album_release_date"].value_counts().head(10)

album_release_date
2012-11-13    8
2020-03-27    7
2012-10-22    5
2015-11-13    5
2011-01-01    5
2010-05-11    4
2013-01-01    4
2016-05-20    4
2015-11-20    4
2006-01-01    3
Name: count, dtype: int64

In [37]:
print("Duplicate Track IDs:", df_track["track_id"].duplicated().sum())

print(
    "Duplicate track and artist:",
    df_track.duplicated(
        subset=["track_name", "artist_name"]
    ).sum()
)

Duplicate Track IDs: 0
Duplicate track and artist: 850

In [38]:
duplicate_tracks = df_track[
    df_track.duplicated(
        subset=["track_name", "artist_name"],
        keep=False
    )
]

print("Rows involved:", len(duplicate_tracks))

Rows involved: 1548

In [39]:
duplicate_tracks[
    [
        "track_id",
        "track_name",
        "artist_name",
        "album_name",
        "album_release_date",
        "album_type",
        "track_popularity"
    ]
].sort_values(
    by=["track_name", "artist_name"]
).head(30)

,track_id,track_name,artist_name,album_name,album_release_date,album_type,track_popularity
4617,7uX3gufAoBVqKVoD3dBLLD,&burn (with Vince Staples),Billie Eilish,&burn (with Vince Staples),2017-12-15,single,56
5944,6X7qcg95CAeJpTjtg1wooM,&burn (with Vince Staples),Billie Eilish,dont smile at me,2017-12-22,single,59
5953,05od2qm2MTSKCHxy1GBp5W,12 to 12,sombr,I Barely Know Her,2025-08-22,album,89
7597,6MrLkXsMmHaYt680fhJUAq,12 to 12,sombr,12 to 12,2025-07-24,single,85
200,2ULNeSomDxVNmdDy8VxEBU,22,Taylor Swift,Red,2012-10-22,album,58
4949,2P5gfMtCcKP0CkmgqFMyPg,22,Taylor Swift,reputation Stadium Tour Surprise Song Playlist,2017-11-09,album,33
6871,3WC5CVAahvn98hiseoIvbw,22,Taylor Swift,Red (Deluxe Edition),2012-10-22,album,59
6937,5ybJm6GczjQOgTqmJ0BomP,22,Taylor Swift,Red,2012-10-22,album,0
8430,6ce41JVa6KFaryfmC2bu2W,22,Taylor Swift,Red (Big Machine Radio Release Special),2012-10-22,album,64
1960,5kqIPrATaCc2LqxVWzQGbk,7 Years,Lukas Graham,Lukas Graham,2016-04-01,album,83
5728,2vDT1uU6hZgdp3PbWGr0Xy,7 Years,Lukas Graham,7 Years,2015-10-22,single,0
2262,3Yvi5NkUrSppVwrMHYkB6u,A Gift Of A Thistle,James Horner,Braveheart (Original Motion Picture Soundtrack),1995-01-01,album,60
2657,7MGFhIe9CBI5baTwLMj7iE,A Gift Of A Thistle,James Horner,Braveheart - Original Motion Picture Soundtrack,1995-01-01,album,0
3999,0pxPNTroZcxXA0w6IDgMQJ,A Little Death,The Neighbourhood,I Love You. (10th Anniversary Edition),2013-04-23,album,75
4137,0Ot6e3wYVQQ1Us9PM977jE,A Little Death,The Neighbourhood,"Thank You,",2012-12-18,single,70
5087,73OX8GdpOeGzKC6OvGSbsv,A Place in this World,Taylor Swift,Taylor Swift,2006-10-24,album,52
7845,2RSYYe7LhKFxIi50T5XtUo,A Place in this World,Taylor Swift,reputation Stadium Tour Surprise Song Playlist,2017-11-09,album,24
1378,6Qm9MaditCcx5V62rVHYqu,A Thousand Miles,Vanessa Carlton,Best Of,2011-01-01,compilation,60
5270,5y69gQtK33qxb8a24ACkCy,A Thousand Miles,Vanessa Carlton,Be Not Nobody,2002-04-30,album,0
2483,4wJ5Qq0jBN4ajy7ouZIV1c,APT.,ROSÉ,rosie,2024-12-06,album,83
4796,5vNRhkKd0yEAg8suGBpjeY,APT.,ROSÉ,APT.,2024-10-18,single,88
3312,2LHNTC9QZxsL3nWpt8iaSR,Abracadabra,Lady Gaga,MAYHEM,2025-03-07,album,81
4088,5ZLUm9eab8y3tqQ1OhQSHI,Abracadabra,Lady Gaga,Abracadabra,2025-02-03,single,81
8260,4vcDr56fq4Jjxpegx3XPnv,Abracadabra,Lady Gaga,MAYHEM,2025-09-01,album,62
3730,17UoqnSRKmsWbhInoFGq4F,Acquainted,The Weeknd,The Highlights (Deluxe),2024-02-09,compilation,39
7301,1m5kZFmm90hPXzXr1Hpsne,Acquainted,The Weeknd,The Highlights,2021-02-05,compilation,39
8635,7uJH0YdSZL6psjxI6Xy08b,Acquainted,The Weeknd,Beauty Behind The Madness,2015-08-28,album,73
3222,0zCgWGmDF0aih5qexATyBn,After Dark,Mr.Kitty,Time,2014-08-08,album,2
6598,5FkJHVudUByVjanCqFXRql,After Dark,Mr.Kitty,Time,2014-08-08,album,63
3732,4ejyZ4uJEXUURcgKp1kP8v,After Hours,The Weeknd,After Hours,2020-02-19,single,1

In [40]:
matching_tracks = track_only.merge(
    df_spotify,
    on=["track_name", "artist_name"],
    how="inner",
    suffixes=("_track", "_spotify")
)

matched_ids = matching_tracks["track_id_track"].nunique()

print("Excluded track IDs:", len(track_only))
print("Matched by track name and artist:", matched_ids)
print("No matching track and artist:", len(track_only) - matched_ids)

Excluded track IDs: 196
Matched by track name and artist: 190
No matching track and artist: 6

In [41]:
matched_track_ids = matching_tracks["track_id_track"].unique()

unmatched_tracks = track_only[
    ~track_only["track_id"].isin(matched_track_ids)
]

print("Unmatched tracks:", len(unmatched_tracks))

Unmatched tracks: 6

In [42]:
unmatched_tracks[
    [
        "track_id",
        "track_name",
        "artist_name",
        "track_popularity",
        "artist_popularity",
        "artist_followers",
        "artist_genres",
        "album_name",
        "album_release_date",
        "album_type",
        "track_duration_min"
    ]
]

,track_id,track_name,artist_name,track_popularity,artist_popularity,artist_followers,artist_genres,album_name,album_release_date,album_type,track_duration_min
3287,0by9UaVYUrKUz2TVAmK0Pg,Calling (Spider-Man: Across the Spider-Verse) ...,Metro Boomin,0,84.0,11679132.0,[],METRO BOOMIN PRESENTS SPIDER-MAN: ACROSS THE S...,2023-06-05,album,3.657550
3495,5rurggqwwudn9clMdcchxT,Calling (Spider-Man: Across the Spider-Verse) ...,Metro Boomin,70,84.0,11679132.0,[],METRO BOOMIN PRESENTS SPIDER-MAN: ACROSS THE S...,2023-06-02,album,3.657550
3618,37ns6v0HK4zMV1PpRLIsbx,NaN,Various Artists,0,0.0,2777475.0,[],NaN,0000,single,0.000000
4170,6N21iOdTYgYjDK1AyS0iUW,NaN,Various Artists,0,0.0,2777927.0,[],NaN,0000,single,0.000000
6709,62oaDoBveZxvZb94ziiMXi,Somebody That I Used to Know,Gotye,60,68.0,2257047.0,[],Making Mirrors,2011-08-19,album,4.095917
7102,3Dknan6iov4lBCwyHHinhS,"The Pirate That Should Not Be - From ""Pirates ...",Rodrigo y Gabriela,37,47.0,462875.0,[],Pirates of the Caribbean: On Stranger Tides,2011-01-01,compilation,3.893767

In [43]:
df_track[
    df_track["track_id"] == "3Dknan6iov4lBCwyHHinhS"
].T

                                                                 7102
track_id                                       3Dknan6iov4lBCwyHHinhS
track_name          The Pirate That Should Not Be - From "Pirates ...
track_number                                                        4
track_popularity                                                   37
explicit                                                        False
artist_name                                        Rodrigo y Gabriela
artist_popularity                                                47.0
artist_followers                                             462875.0
artist_genres                                                      []
album_id                                       2RkWo1xomg2mBR8ydABsab
album_name                Pirates of the Caribbean: On Stranger Tides
album_release_date                                         2011-01-01
album_total_tracks                                                 18
album_type                                                compilation
track_duration_min                                           3.893767

In [44]:
df_track[
    df_track["track_name"].str.contains(
        "Pirate That Should Not Be",
        case=False,
        na=False
    )
].T

                                                                 7102
track_id                                       3Dknan6iov4lBCwyHHinhS
track_name          The Pirate That Should Not Be - From "Pirates ...
track_number                                                        4
track_popularity                                                   37
explicit                                                        False
artist_name                                        Rodrigo y Gabriela
artist_popularity                                                47.0
artist_followers                                             462875.0
artist_genres                                                      []
album_id                                       2RkWo1xomg2mBR8ydABsab
album_name                Pirates of the Caribbean: On Stranger Tides
album_release_date                                         2011-01-01
album_total_tracks                                                 18
album_type                                                compilation
track_duration_min                                           3.893767

In [45]:
df_track["album_release_date"].head(20)

0     2009-11-09
1     2023-01-13
2     2021-04-09
3     2021-07-30
4     2010-01-01
5     2015-08-28
6     2017-12-22
7     2024-09-27
8     2014-06-21
9     2020-07-20
10    2012-03-12
11    2022-07-21
12    2003-11-13
13    2024-03-20
14    2023-02-24
15    2015-07-10
16    2014-01-01
17    2017-04-14
18    2018-11-14
19    2008-06-17
Name: album_release_date, dtype: str

In [46]:
df_track["album_release_date"].astype(str).str.len().value_counts()

album_release_date
10    8577
4      198
7        3
Name: count, dtype: int64

In [47]:
df_track[
    ["album_release_date"]
].assign(
    date_length=df_track["album_release_date"].astype(str).str.len()
).drop_duplicates().sort_values("date_length").head(30)

     album_release_date  date_length
92                 2005            4
1355               1997            4
147                1959            4
6103               2018            4
6961               1971            4
247                1973            4
1707               1993            4
67                 2007            4
1138               2013            4
4118               1996            4
6935               1962            4
1318               2008            4
6508               1985            4
1019               2006            4
2680               1987            4
49                 1980            4
1689               2011            4
2282               2003            4
1074               1967            4
1128               1974            4
8047               1970            4
508                2016            4
2909               1992            4
1159               2001            4
1093               1966            4
685                2015            4
7266               1994            4
1367               1977            4
2927               1989            4
318                1979            4

In [49]:
print(
    "Invalid 0000 dates:",
    (df_track["album_release_date"] == "0000").sum()
)

Invalid 0000 dates: 2

In [50]:
year_only = df_track[
    df_track["album_release_date"].str.len() == 4
]

year_only["album_release_date"].value_counts().sort_index()

album_release_date
0000     2
1959     3
1962     1
1963     1
1966     3
1967     7
1970     1
1971     1
1972     3
1973     1
1974     1
1975     1
1976     6
1977     2
1978     4
1979     2
1980     2
1981     1
1984     2
1985     2
1986     1
1987     3
1989     1
1992     1
1993     2
1994     1
1995     3
1996     3
1997     4
1998     3
1999     6
2000     6
2001     8
2002     6
2003     6
2004    10
2005     8
2006     7
2007    10
2008     6
2009    13
2010    11
2011     6
2012     5
2013     7
2014     4
2015     3
2016     5
2017     2
2018     1
Name: count, dtype: int64

In [51]:
year_month = df_track[
    df_track["album_release_date"].str.len() == 7
]

year_month[
    ["track_name", "artist_name", "album_release_date"]
]

,track_name,artist_name,album_release_date
2394,Tainted Love - Remastered 2008,Soft Cell,1981-12
4752,Brown Eyed Girl,Van Morrison,1967-09
4887,I'd Love to Change the World - 2004 Remaster,Ten Years After,1971-08

In [52]:
year_month = df_track[
    df_track["album_release_date"].str.len() == 7
]

year_month[
    ["track_name", "artist_name", "album_release_date"]
]

,track_name,artist_name,album_release_date
2394,Tainted Love - Remastered 2008,Soft Cell,1981-12
4752,Brown Eyed Girl,Van Morrison,1967-09
4887,I'd Love to Change the World - 2004 Remaster,Ten Years After,1971-08

In [53]:
df_track[
    df_track["album_release_date"] == "0000"
][
    [
        "track_id",
        "track_name",
        "artist_name",
        "album_name",
        "album_release_date"
    ]
]

,track_id,track_name,artist_name,album_name,album_release_date
3618,37ns6v0HK4zMV1PpRLIsbx,NaN,Various Artists,NaN,0000
4170,6N21iOdTYgYjDK1AyS0iUW,NaN,Various Artists,NaN,0000