In [3]:
from pathlib import Path
import pandas as pd
import numpy as np

PROJECT_ROOT = Path.home() / "Documents" / "spotify_project"

RAW_DATA = PROJECT_ROOT / "data" / "raw"
CLEAN_DATA = PROJECT_ROOT / "data" / "clean"
FIGURES = PROJECT_ROOT / "figures"

In [5]:
print("Project:", PROJECT_ROOT)
print("Raw data:", RAW_DATA)
print("Clean data:", CLEAN_DATA)

Project: /Users/jannoelvero/Documents/spotify_project
Raw data: /Users/jannoelvero/Documents/spotify_project/data/raw
Clean data: /Users/jannoelvero/Documents/spotify_project/data/clean

In [6]:
print(list(RAW_DATA.iterdir()))

[PosixPath('/Users/jannoelvero/Documents/spotify_project/data/raw/spotify_data_clean.csv'), PosixPath('/Users/jannoelvero/Documents/spotify_project/data/raw/.gitkeep'), PosixPath('/Users/jannoelvero/Documents/spotify_project/data/raw/track_data_final.csv')]

In [7]:
df_track = pd.read_csv(RAW_DATA / "track_data_final.csv")
df_spotify = pd.read_csv(RAW_DATA / "spotify_data_clean.csv")

In [8]:
print("Track dataset:", df_track.shape)
print("Spotify dataset:", df_spotify.shape)

Track dataset: (8778, 15)
Spotify dataset: (8582, 15)

In [10]:
df = df_track.copy()

In [11]:
df.shape

(8778, 15)

In [12]:
df = df[df["album_release_date"] != "0000"].copy()

In [13]:
df.shape

(8776, 15)

In [14]:
df.isnull().sum()

track_id              0
track_name            0
track_number          0
track_popularity      0
track_duration_ms     0
explicit              0
artist_name           4
artist_popularity     4
artist_followers      4
artist_genres         4
album_id              0
album_name            0
album_release_date    0
album_total_tracks    0
album_type            0
dtype: int64

In [15]:
df[df["artist_name"].isnull()][
    [
        "track_id",
        "track_name",
        "artist_name",
        "artist_popularity",
        "artist_followers",
        "artist_genres"
    ]
]

,track_id,track_name,artist_name,artist_popularity,artist_followers,artist_genres
436,3QhfFRPkhPCR1RMJWV1gde,Radio,NaN,NaN,NaN,NaN
1396,2NbsBSshscKIPRG3kwBbfo,Never Felt So Alone,NaN,NaN,NaN,NaN
3885,5EhZC8GFOVXrpiUW22jncE,Urban Twilight,NaN,NaN,NaN,NaN
3886,0fM9dEhUFV4MHDuJgrcfOv,How You Get The Girl,NaN,NaN,NaN,NaN

In [16]:
missing_ids = df[df["artist_name"].isnull()]["track_id"]

df_spotify[
    df_spotify["track_id"].isin(missing_ids)
][
    [
        "track_id",
        "track_name",
        "artist_name",
        "artist_popularity",
        "artist_followers",
        "artist_genres"
    ]
]

,track_id,track_name,artist_name,artist_popularity,artist_followers,artist_genres
1807,2NbsBSshscKIPRG3kwBbfo,Never Felt So Alone,NaN,0,0,NaN
5904,0fM9dEhUFV4MHDuJgrcfOv,How You Get The Girl,Taylor Swift,100,145396321,"country, pop, indie, folk"
6517,3QhfFRPkhPCR1RMJWV1gde,Radio,NaN,0,0,NaN
6679,5EhZC8GFOVXrpiUW22jncE,Urban Twilight,NaN,0,0,NaN

In [17]:
track_id = "0fM9dEhUFV4MHDuJgrcfOv"

df.loc[df["track_id"] == track_id, "artist_name"] = "Taylor Swift"
df.loc[df["track_id"] == track_id, "artist_popularity"] = 100
df.loc[df["track_id"] == track_id, "artist_followers"] = 145396321
df.loc[df["track_id"] == track_id, "artist_genres"] = "country, pop, indie, folk"

In [18]:
df[df["track_id"] == track_id][
    [
        "track_name",
        "artist_name",
        "artist_popularity",
        "artist_followers",
        "artist_genres"
    ]
]

,track_name,artist_name,artist_popularity,artist_followers,artist_genres
3886,How You Get The Girl,Taylor Swift,100.0,145396321.0,"country, pop, indie, folk"

In [19]:
df[df["artist_name"].isnull()][
    [
        "track_id",
        "track_name",
        "album_name",
        "album_release_date",
        "track_popularity"
    ]
]

,track_id,track_name,album_name,album_release_date,track_popularity
436,3QhfFRPkhPCR1RMJWV1gde,Radio,Born To Die – Paradise Edition (Special Version),2012-01-01,65
1396,2NbsBSshscKIPRG3kwBbfo,Never Felt So Alone,Never Felt So Alone,2023-04-07,68
3885,5EhZC8GFOVXrpiUW22jncE,Urban Twilight,Darkbloom,2011-04-18,30

In [20]:
df[
    df["track_name"].isin(
        ["Radio", "Never Felt So Alone", "Urban Twilight"]
    )
][
    [
        "track_name",
        "artist_name",
        "artist_popularity",
        "artist_followers",
        "artist_genres",
        "album_name"
    ]
]

,track_name,artist_name,artist_popularity,artist_followers,artist_genres,album_name
436,Radio,NaN,NaN,NaN,NaN,Born To Die – Paradise Edition (Special Version)
1038,Radio,Lana Del Rey,88.0,51773650.0,[],Born To Die (Deluxe Version)
1396,Never Felt So Alone,NaN,NaN,NaN,NaN,Never Felt So Alone
3885,Urban Twilight,NaN,NaN,NaN,NaN,Darkbloom
8759,Radio,Lana Del Rey,88.0,51847587.0,[],Born To Die - The Paradise Edition

In [21]:
df.loc[
    df["track_id"] == "3QhfFRPkhPCR1RMJWV1gde",
    "artist_name"
] = "Lana Del Rey"

In [22]:
df[df["track_id"] == "3QhfFRPkhPCR1RMJWV1gde"][
    ["track_name", "artist_name", "artist_popularity", "artist_followers", "artist_genres"]
]

,track_name,artist_name,artist_popularity,artist_followers,artist_genres
436,Radio,Lana Del Rey,NaN,NaN,NaN

In [23]:
df[
    df["album_name"] == "Never Felt So Alone"
][
    [
        "track_name",
        "artist_name",
        "artist_popularity",
        "artist_followers",
        "artist_genres",
        "album_name"
    ]
]

,track_name,artist_name,artist_popularity,artist_followers,artist_genres,album_name
1396,Never Felt So Alone,NaN,NaN,NaN,NaN,Never Felt So Alone

In [24]:
df[
    df["track_name"] == "Urban Twilight"
][
    [
        "track_name",
        "artist_name",
        "artist_popularity",
        "artist_followers",
        "artist_genres",
        "album_name"
    ]
]

,track_name,artist_name,artist_popularity,artist_followers,artist_genres,album_name
3885,Urban Twilight,NaN,NaN,NaN,NaN,Darkbloom

In [25]:
df.isnull().sum()

track_id              0
track_name            0
track_number          0
track_popularity      0
track_duration_ms     0
explicit              0
artist_name           2
artist_popularity     3
artist_followers      3
artist_genres         3
album_id              0
album_name            0
album_release_date    0
album_total_tracks    0
album_type            0
dtype: int64

In [26]:
df["track_duration_min"] = (
    df["track_duration_ms"] / 60000
).round(2)

In [27]:
df = df.drop(columns=["track_duration_ms"])

In [28]:
df[["track_name", "track_duration_min"]].head()

                            track_name  track_duration_min
0                                    3                3.55
1                               Clouds                2.65
2  Forever & Always (Taylor’s Version)                3.76
3            I Didn't Change My Number                2.64
4                             Man Down                4.45

In [29]:
df["artist_genres"].head(20)

0                                               ['pop']
1                                     ['stutter house']
2                                                    []
3                                                    []
4                                                    []
5                                         ['dream pop']
6                                                    []
7     ['brazilian bass', 'electronic', 'slap house',...
8                                          ['soft pop']
9                                                    []
10                                              ['pop']
11           ['uk drill', 'drill', 'uk grime', 'grime']
12                                              ['pop']
13                                ['edm', 'electronic']
14                                                   []
15                                                   []
16                                                   []
17                    ['hip hop', 'west coast hip hop']
18                                                   []
19                                              ['pop']
Name: artist_genres, dtype: str

In [30]:
df["artist_genres"].value_counts(dropna=False).head(20)

artist_genres
[]                                                                            4490
['soundtrack']                                                                 346
['pop']                                                                        303
['soft pop']                                                                   209
['rap']                                                                        192
['dark r&b']                                                                   111
['k-pop']                                                                       93
['grunge', 'rock']                                                              91
['country']                                                                     90
['edm']                                                                         82
['rap', 'hip hop']                                                              77
['country', 'acoustic country']                                                 73
['art pop', 'pop']                                                              72
['r&b']                                                                         65
['emo rap', 'cloud rap']                                                        63
['reggaeton', 'trap latino', 'urbano latino', 'latin']                          56
['bedroom pop']                                                                 50
['rage rap']                                                                    49
['industrial metal', 'industrial rock', 'industrial', 'metal', 'nu metal']      48
['anime', 'soundtrack']                                                         46
Name: count, dtype: int64

In [31]:
df["artist_genres"] = df["artist_genres"].replace("[]", np.nan)

In [32]:
df["artist_genres"].isnull().sum()

np.int64(4493)

In [33]:
df["artist_genres"] = (
    df["artist_genres"]
    .str.replace("[", "", regex=False)
    .str.replace("]", "", regex=False)
    .str.replace("'", "", regex=False)
)

In [34]:
df["artist_genres"].value_counts().head(10)

artist_genres
soundtrack      346
pop             303
soft pop        209
rap             192
dark r&b        111
k-pop            93
grunge, rock     91
country          90
edm              82
rap, hip hop     77
Name: count, dtype: int64

In [35]:
df["release_year"] = pd.to_numeric(
    df["album_release_date"].str[:4],
    errors="coerce"
)

In [36]:
df[["album_release_date", "release_year"]].head(10)

  album_release_date  release_year
0         2009-11-09          2009
1         2023-01-13          2023
2         2021-04-09          2021
3         2021-07-30          2021
4         2010-01-01          2010
5         2015-08-28          2015
6         2017-12-22          2017
7         2024-09-27          2024
8         2014-06-21          2014
9         2020-07-20          2020

In [37]:
print("Earliest year:", df["release_year"].min())
print("Latest year:", df["release_year"].max())

Earliest year: 1952
Latest year: 2025

In [38]:
print("Missing release years:", df["release_year"].isnull().sum())

Missing release years: 0

In [39]:
df[
    [
        "track_popularity",
        "artist_popularity",
        "artist_followers",
        "album_total_tracks",
        "track_duration_min"
    ]
].describe()

,track_popularity,artist_popularity,artist_followers,album_total_tracks,track_duration_min
count,8776.000000,8773.000000,8.773000e+03,8776.000000,8776.000000
mean,52.244758,69.974353,2.437358e+07,13.782589,3.503447
std,24.065045,19.507944,3.816035e+07,11.797828,1.054251
min,0.000000,0.000000,0.000000e+00,1.000000,0.070000
25%,39.000000,60.000000,5.148960e+05,6.000000,2.900000
50%,58.000000,74.000000,6.294820e+06,13.000000,3.450000
75%,71.000000,84.000000,3.055055e+07,17.000000,4.000000
max,100.000000,100.000000,1.455421e+08,181.000000,13.520000

In [40]:
df[df["track_duration_min"] < 0.5][
    [
        "track_name",
        "artist_name",
        "track_duration_min",
        "track_popularity",
        "album_name"
    ]
].sort_values("track_duration_min")

,track_name,artist_name,track_duration_min,track_popularity,album_name
577,Up next: A few songs,Spotify,0.07,0,Daily Wellness
177,Dorothy's Interlude,Sam Smith,0.15,0,Gloria (Special Edition)
1332,EUROPA :),Bad Bunny,0.20,13,nadie sabe lo que va a pasar mañana
8115,I Can't Fucking Sing,The Weeknd,0.20,18,Hurry Up Tomorrow
5783,'Let's Just Sit',Marion McPherson,0.22,0,Lady Bird - Soundtrack from the Motion Picture
1990,!!!!!!!,Billie Eilish,0.23,17,"WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?"
5518,Hurting Interlude,Sam Smith,0.31,0,Gloria (Special Edition)
5788,Until We're Skin & Bones,The Weeknd,0.37,21,Hurry Up Tomorrow
311,Paul Rosenberg - Skit,Eminem,0.38,10,The Eminem Show
7451,Her Majesty - Remastered 2009,The Beatles,0.43,27,Abbey Road (Remastered)

In [41]:
df[df["artist_name"] == "Spotify"][
    [
        "track_id",
        "track_name",
        "artist_name",
        "track_popularity",
        "artist_popularity",
        "artist_followers",
        "artist_genres",
        "album_name",
        "album_type",
        "track_duration_min"
    ]
]

,track_id,track_name,artist_name,track_popularity,artist_popularity,artist_followers,artist_genres,album_name,album_type,track_duration_min
577,1aS3BzYaUDJaOdqixzknaz,Up next: A few songs,Spotify,0,16.0,33465.0,NaN,Daily Wellness,single,0.07

In [42]:
df = df[df["artist_name"] != "Spotify"].copy()

In [43]:
df.shape

(8775, 16)

In [44]:
print("Duplicate track IDs:", df["track_id"].duplicated().sum())

Duplicate track IDs: 0

In [45]:
df["explicit"].value_counts(dropna=False)

explicit
False    6584
True     2191
Name: count, dtype: int64

In [46]:
df["album_type"].value_counts(dropna=False)

album_type
album          6022
single         2245
compilation     508
Name: count, dtype: int64

In [47]:
df["track_number"].describe()

count    8775.000000
mean        5.750427
std         6.018619
min         1.000000
25%         1.000000
50%         4.000000
75%         9.000000
max       102.000000
Name: track_number, dtype: float64

In [48]:
df[df["track_number"] > 50][
    [
        "track_name",
        "artist_name",
        "track_number",
        "album_name",
        "album_total_tracks",
        "album_type"
    ]
].sort_values("track_number", ascending=False)

,track_name,artist_name,track_number,album_name,album_total_tracks,album_type
3674,I Don't Want This Night To End,Luke Bryan,102,Best Country Of The Decade: 2011-2020,136,compilation
8336,Aguas da Amazonia: Japurá River,Philip Glass,70,Landscapes: Minimalism,100,compilation
3258,Zombie,The Cranberries,66,The Best 90s Album In The World...Ever!,77,compilation
0,3,Britney Spears,57,The Singles Collection,58,compilation
6145,Another Round For Everyone,Marcin Przybyłowicz,54,The Witcher 3: Wild Hunt (Original Game Soundt...,55,album
7682,Shaun of the Dead Main Theme (Instrumental Mix),Halloween All-Stars,52,The House of Hallowe'en - Classic Halloween Ho...,60,compilation

In [49]:
invalid_track_numbers = df[
    df["track_number"] > df["album_total_tracks"]
]

print("Invalid track numbers:", len(invalid_track_numbers))

Invalid track numbers: 0

In [50]:
print("Track popularity:", df["track_popularity"].min(), "to", df["track_popularity"].max())
print("Artist popularity:", df["artist_popularity"].min(), "to", df["artist_popularity"].max())

Track popularity: 0 to 100
Artist popularity: 0.0 to 100.0

In [51]:
print("Minimum followers:", df["artist_followers"].min())
print("Negative followers:", (df["artist_followers"] < 0).sum())

Minimum followers: 0.0
Negative followers: 0

In [52]:
df.info()

<class 'pandas.DataFrame'>
Index: 8775 entries, 0 to 8777
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   track_id            8775 non-null   str
 1   track_name          8775 non-null   str
 2   track_number        8775 non-null   int64
 3   track_popularity    8775 non-null   int64
 4   explicit            8775 non-null   bool
 5   artist_name         8773 non-null   str
 6   artist_popularity   8772 non-null   float64
 7   artist_followers    8772 non-null   float64
 8   artist_genres       4283 non-null   str
 9   album_id            8775 non-null   str
 10  album_name          8775 non-null   str
 11  album_release_date  8775 non-null   str
 12  album_total_tracks  8775 non-null   int64
 13  album_type          8775 non-null   str
 14  track_duration_min  8775 non-null   float64
 15  release_year        8775 non-null   int64
dtypes: bool(1), float64(3), int64(4), str(8)
memory usage: 1.1 MB

In [53]:
df = df.reset_index(drop=True)

In [54]:
df.tail()

,track_id,track_name,track_number,track_popularity,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type,track_duration_min,release_year
8770,58VTP6KnZs12PcAj5rMJ4W,the fruits,1,65,False,Paris Paloma,66.0,786890.0,NaN,48ssTnnFOCIP17sRaFNqu1,the fruits,2022-04-29,1,single,3.49,2022
8771,2dRfUOeTVpr4V4PmmqGkpm,Dark World Theme (The Legend of Zelda),4,2,False,Zelda,8.0,3263.0,NaN,0JJAfVZtn3EvZnXSQrpLSh,The Legend of Zelda,2023-08-19,7,album,1.89,2023
8772,37F0uwRSrdzkBiuj0D5UHI,Reminder,4,81,True,The Weeknd,94.0,113039308.0,NaN,2ODvWsOgouMbaA5xf0RkJe,Starboy,2016-11-25,18,album,3.65,2016
8773,42qNWdLKCI41S4uzfamhFM,Duvet,1,84,False,bôa,68.0,1188508.0,NaN,7sGYAV0xv7ZfAMzIpMl8m1,Twilight,2001-03-21,14,album,3.39,2001
8774,7KZJnMtwu2s80jO5Frthap,So Much Better,4,33,True,Eminem,88.0,104584370.0,"rap, hip hop",3vOgbDjgsZBAPwV2M3bNOj,The Marshall Mathers LP2,2013-11-05,16,album,4.36,2013

In [55]:
df.isnull().sum()

track_id                 0
track_name               0
track_number             0
track_popularity         0
explicit                 0
artist_name              2
artist_popularity        3
artist_followers         3
artist_genres         4492
album_id                 0
album_name               0
album_release_date       0
album_total_tracks       0
album_type               0
track_duration_min       0
release_year             0
dtype: int64

In [56]:
print("Duplicate rows:", df.duplicated().sum())
print("Duplicate track IDs:", df["track_id"].duplicated().sum())

Duplicate rows: 0
Duplicate track IDs: 0

In [57]:
df.to_csv(CLEAN_DATA / "spotify_final.csv", index=False)

In [58]:
print((CLEAN_DATA / "spotify_final.csv").exists())

True

In [59]:
df_final = pd.read_csv(CLEAN_DATA / "spotify_final.csv")

In [60]:
print("Final dataset shape:", df_final.shape)

Final dataset shape: (8775, 16)

In [61]:
print("Duplicate rows:", df_final.duplicated().sum())
print("Duplicate track IDs:", df_final["track_id"].duplicated().sum())
print("Missing values:")
print(df_final.isnull().sum())

Duplicate rows: 0
Duplicate track IDs: 0
Missing values:
track_id                 0
track_name               0
track_number             0
track_popularity         0
explicit                 0
artist_name              2
artist_popularity        3
artist_followers         3
artist_genres         4492
album_id                 0
album_name               0
album_release_date       0
album_total_tracks       0
album_type               0
track_duration_min       0
release_year             0
dtype: int64

In [62]:
mysql_file = CLEAN_DATA / "spotify_mysql.csv"

df_final.to_csv(
    mysql_file,
    index=False,
    encoding="utf-8-sig"
)

print(mysql_file)

/Users/jannoelvero/Documents/spotify_project/data/clean/spotify_mysql.csv

/Users/jannoelvero/Documents/spotify_project/data/clean/spotify_mysql.csv